twig:
    default_path: '%kernel.project_dir%/templates'
    debug: true
    globals:
        GOOGLE_RECAPTCHA_SITE_KEY: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        PAYPAL_SDK_CLIENT_ID: '%env(PAYPAL_SDK_CLIENT_ID)%'
